config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :dashboard
    resources :conversations
    resources :messages
    resources :topics
    resources :admin

    root 'conversations#index'

    get 'conversations_controller/index'
    get '/users', to: 'conversations#index'

    match 'users/:id' => 'users#edit', :via => :update, :as => :admin_update_user
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

    authenticate :user do
        mount ActionCable.server => '/cable'
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_navigation.html.erb
<div class="list-content">
	<div class="application-name">
		<%= link_to "Breakroom", root_path %>
	</div>
	<div class="channel-tab">
		<h3>CHANNELS</h3>
		<ul>
			<%= render @topics %>
		</ul>
	</div>
	<div class="profile-tab">
		<h3>Profile</h3>
		<div class="edit-profile-btn">
			<%= link_to "Edit", edit_user_registration_path %>
		</div>
		<div class="profile-info-container">
			<div class="profile-avatar">
				<%= gravatar_for current_user %>
			</div>
			<div class="profile-name">
				@
				<%= current_user.name %>
				<div class="profile-email">
					<%= current_user.email %>
				</div>
			</div>
			<div class="logout">
				<%= link_to image_tag('http://res.cloudinary.com/unique/image/upload/v1479713991/exit_nfqhkf.png'), destroy_user_session_path, method: :delete %>
			</div>
		</div>
		<% if current_user.is_admin?%>
			<div class="admin-tab">
				<a>ADMIN OPTIONS</a>
				<div class="admin-options">
					<br />
					<%= link_to "View users", admin_index_path %>
				</div>
			</div>
		<% end %>
	</div>
</div>