config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :dashboard
    resources :conversations
    resources :messages
    resources :topics
    resources :admin

    root 'conversations#index'

    get 'conversations_controller/index'
    get '/users', to: 'conversations#index'

    match 'users/:id' => 'users#edit', :via => :update, :as => :admin_update_user
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

    authenticate :user do
        mount ActionCable.server => '/cable'
    end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :user
    has_many :messages, dependent: :destroy
    belongs_to :topic

    validates :title, presence: true, length: {minimum: 2, maximum: 100}
    validates :topic_id, presence: true
    validates :description, presence: true, length: {minimum: 5, maximum: 200}

    def timestamp
        created_at.strftime('%b %d at %I:%M %p')
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_page, only: [:index]
    TOPICS_PER_PAGE = 10
    CONVERSATIONS_PER_PAGE = 5

    def index
        @display_next = @all_topics.count > TOPICS_PER_PAGE * (@page + 1)
        @topic_filters = @all_topics.offset(TOPICS_PER_PAGE * @page).limit(TOPICS_PER_PAGE).load
        @conversations = Conversation.where(topic_id: session[:topic_ids]).order('created_at DESC').offset(CONVERSATIONS_PER_PAGE * @conversation_page).limit(CONVERSATIONS_PER_PAGE).load
    end

    def new
        @conversation = Conversation.new
    end

    def show
        @conversation = Conversation.includes(:messages).find_by(id: params[:id])
        @message = Message.new
        @conversations = Conversation.all
    end

    def create
        @conversation = current_user.conversations.build(conversation_params) unless current_user.blank?
        if @conversation.save
            flash[:notice] = 'Conversation added!'
            redirect_to conversations_path
        else
            flash.now[:error] = @conversation.errors.map{|e,m|e.to_s.humanize.to_s + " " + m}
            respond_to do |format|
                format.js { render 'conversations/create'}
            end
        end
    end

    def edit
        @conversation = Conversation.find(params[:id])
    end

    def update
        @conversation = Conversation.find(params[:id])

        if @conversation.update_attributes(conversation_params)
            redirect_to @conversation
        else
            flash.now[:error] = @conversation.errors.map{|e,m|e.to_s.humanize.to_s + " " + m}
            respond_to do |format|
                format.js { render 'conversations/update'}
            end
        end
    end

    def destroy
        @conversation = Conversation.find(params[:id]).destroy
        flash[:notice] = "Conversation deleted"
        redirect_to root_path
    end

    private

    def conversation_params
        params.require(:conversation).permit(:title, :description, :topic_id, :url)
    end

    def set_page
        @page = (params[:topics_page] || 0).to_i
        @conversation_page = (params[:conversation_page] || 0).to_i
        @all_topics = Topic.where(organization_id: [current_user.organization_id, nil])
        topic_ids = @all_topics.map(&:id)
        topic_id = params[:topic_id].to_i
        if params[:topic_id].present?
            if params[:topic_id] == 'all'
                session[:topic_ids] = topic_ids
            elsif @all_topics.count == session[:topic_ids].count || params[:single_topic].present?
                session[:topic_ids] = [topic_id]
            elsif session[:topic_ids].include?(topic_id)
                session[:topic_ids] = session[:topic_ids] - [topic_id]
            else
                session[:topic_ids] << topic_id
            end
        elsif session[:topic_ids].blank?
            session[:topic_ids] = topic_ids
        end
    end
end

app/views/conversations/_conversation.html.erb
    <div class="card mx-auto mb-2 shadow-sm p-3 bg-white rounded" style="width: 100%;">
        <div class="card-body text-left">
            <a href="<%= conversations_path(page: @page, topic_id: conversation.topic_id, single_topic: true) %>" data-remote=true class="btn btn-dark left above-card"><%= conversation.topic.name %></a>
            <h2 class="card-title"><%= conversation.title %></h2>
            <p class="hint"><%= gravatar_for(conversation.user, {class: 'gravatar-img'}) %> <%= conversation.user.name %> <span class='conversation-timestamp'><%= conversation.timestamp %></span></p>
            <% if conversation.url.present? %><a href="<%= conversation.url %>" target="_blank" class='above-card'><%= conversation.url.truncate(30) %></a><% end %>
            <p><%= conversation.description %></p>
            <% message_count = conversation.messages.count %>
            <p><% User.where(id: conversation.messages.group(:id, :user_id).last(5).pluck(:user_id)).each do |user| %>
            <%= gravatar_for(user, {size: 25, class: 'message-gravatar'}).html_safe %><% end %> <%= "#{message_count.to_s} #{message_count > 1  || message_count == 0 ? 'comments' : 'comment'}" %></p>
            <a href="<%= conversation_path(conversation) %>" class='stretched-link'></a>
        </div>
    </div>

app/views/conversations/_edit.html.erb
<div class="usermodal">
    <% if current_user%>
        <h1>Edit <%= @conversation.title %></h1>

        <%= render 'form' %>
    <% else %>
        <% controller.redirect_to root_path %>
    <% end %>
</div>

app/views/conversations/_form.html.erb
<div id='flash'></div>
<%= form_for @conversation, html: {remote: true} do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: 'form-control', id: "conversation_title" %>
    </div>
    <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, autofocus: true, class: 'form-control', id: "conversation_url" %>
    </div>
    <div class='form-group'>
        <%= f.label :description %>
        <%= f.text_area :description, autofocus: true, class: 'form-control', id: "conversation_description" %>
    </div>
    <div class="form-group">
        <%= f.collection_select(:topic_id, Topic.all, :id, :to_s, {prompt: 'Select Topic'}, class: 'form-control')%>
    </div>

    <span><%= f.submit "Submit!", class: 'btn btn-primary', remote: true %></span>
    <button type='button' class='btn' data-dismiss='modal' aria-hidden='true'>Cancel</button>
<% end %>

app/views/conversations/_list.html.erb
<%= render @thems.conversations %>

app/views/conversations/_new.html.erb
<div class='modal-header'>
	<h4 class='modal-title' id='myModalLabel'>New Conversation</h4>
	<button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
</div>
<div class="modal-body">
	<%= render 'form' %>
</div>

app/views/conversations/_topic_filters.html.erb
<%= link_to 'All', conversations_path(page: @page, topic_id: 'all'), remote: true, method: :get, class: " p-10  #{session[:topic_ids].count == @all_topics.count ? "btn_1" : "btn_2"}" %>
<% @topic_filters.each do |topic| %>
	<%= link_to topic.name, conversations_path(page: @page, topic_id: topic.id), remote: true, method: :get, class: "btn #{session[:topic_ids].include?(topic.id) && session[:topic_ids].count != @all_topics.count ? "btn-dark" : "btn-light"}" %>
<% end %>

app/views/conversations/create.js.erb
$("#AddConversationModal .modal-content").html('<%= j render partial: "conversations/new" %>');
$('#flash').html(('<%= j render partial: "layouts/flash" %>'));
$("#AddConversationModal").modal();

app/views/conversations/edit.html.erb
<div class="usermodal">
    <% if current_user && current_user.is_admin? %>
        <h1>Edit conversation</h1>

        <%= render 'form' %>
    <% else %>
        <% controller.redirect_to root_path %>
    <% end %>
</div>

app/views/conversations/edit.js.erb
 $("#EditConversationModal .modal-content").html('<%= j render partial: "conversations/edit" %>');
 $("#EditConversationModal").modal();

app/views/conversations/index.html.erb
<div class="usermodal">
	<div class="application-name">
		<h1><%= link_to "Breakroom", root_path %></h1>
	</div>
		<%= link_to "logout", destroy_user_session_path, method: :delete %>
	<br/>
	<div class="container">
		<div class="btn-group btn-group-justified">
			<% if @page > 0 %>
				<%= link_to "&larr; ".html_safe, conversations_path(topics_page: @page - 1), class: 'mr-2' %>
			<% end %>
			<div class="conversationButtons" id='topic-filters'>
				<%= render 'topic_filters' %>
			</div>
			<% if @display_next %>
				<%= link_to "&rarr;".html_safe, conversations_path(topics_page: @page + 1), class: 'ml-2' %>
			<% end %>
			<%= button_to '+', new_topic_path, remote: true, method: :get, class: 'btn btn-success btn-block ml-2' %>
		</div>
	</div>
</div>
<div class='new-conversation-btn-box'>
	<%= button_to 'Start a Conversation', new_conversation_path, remote: true, method: :get, class: 'mb-3 new-conversation-btn' %>
</div>

<div class='conversation-cards overflow-auto' data-page="<%= @conversations_page %>" id='conversations-feed'>
	<% if  @conversations.count > 0 %>
	    <%= render @conversations %>
	<% else %>
	   <h5>You've unselected all topics. Hit "All" or choose a topic to see conversations.</h5>
	<% end %>
</div>

<div id='infinite-scrolling'></div>

<div class='modal' id='AddConversationModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
        </div>
    </div>
</div>

<div class='modal' id='AddTopicModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
        </div>
    </div>
</div>

app/views/conversations/index.js.erb
$("#topic-filters").html('<%= j render partial: "topic_filters" %>');
<% if params[:topic_id].present? %>
	<% if @conversations.count > 0 %>
		$('#conversations-feed').html('<%= j render @conversations %>');
	<% else %>
		$('#conversations-feed').html('<h5>You\'ve unselected all topics. Hit "All" or choose a topic to see conversations.</h5>');
	<% end %>
	$('#conversations-feed').data('page', <%= 0 %>);
<% elsif @conversations.count > 0 && params[:conversation_page].present? %>
	$('#conversations-feed').data('page', <%= params[:conversation_page] %>);
    $('#conversations-feed').append('<%= j render @conversations %>');
<% else %>
    $(window).off('scroll');
<% end %>

app/views/conversations/new.js.erb
 $("#AddConversationModal .modal-content").html('<%= j render partial: "conversations/new" %>');
 $("#AddConversationModal").modal();

app/views/conversations/show.html.erb
<header>
    <div class="channelInfo">
        <h1 class='application-title' style='font-weight: bold; margin-right: 2em;'><%= link_to "Breakroom", root_path %></h1>
        <h1 class="assignChannel"><%= @conversation.title %></h1>&nbsp;~&nbsp;
        <h3><%= @conversation.description %></h3>
        <% if @conversation.url.present? %><a href="<%= @conversation.url %>" target="_blank"><%= @conversation.url.truncate(30) %></a><% end %>
    </div>
    <% if current_user.is_admin? %>
        <h4>Admin Tools: <%= link_to "Delete Conversation", conversation_path(@conversation.id), 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?", id: "delete-conversation"%>
         <%= link_to "Edit Conversation",   edit_conversation_path(@conversation.id), :confirm => "Are you sure ?", remote: true%></h4>
    <% end %>

</header>
<div id="messages" data-conversation-id="<%= @conversation.id %>">
    <%= render @conversation.messages %>
</div>

<div class="chatinput">
    <%= form_for @message, url: '#', id: 'formSubmit' do |f| %>
        <%= hidden_field_tag 'conversation_id', @conversation.id %>
        <div>
            <%= f.text_field :body, class: 'form-control', placeholder: 'Type your message...' %>
        </div>
    <% end %>
</div>


<div class='modal' id='EditConversationModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
        </div>
    </div>
</div>

app/views/conversations/update.js.erb
$("#EditConversationModal .modal-content").html('<%= j render partial: "conversations/edit" %>');
$('#flash').html(('<%= j render partial: "layouts/flash" %>'));
$("#EditConversationModal").modal();