config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :dashboard
    resources :conversations
    resources :messages
    resources :topics
    resources :admin

    root 'conversations#index'

    get 'conversations_controller/index'
    get '/users', to: 'conversations#index'

    match 'users/:id' => 'users#edit', :via => :update, :as => :admin_update_user
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

    authenticate :user do
        mount ActionCable.server => '/cable'
    end
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :conversations

    def to_s
        self.name
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :authenticate_user!

    def index
        @topics = Topic.where(organization_id: [current_user.organization_id, nil]).includes(:conversations).load
    end

    def new
        @topic = Topic.new
    end

    def show
        @topic = Topic.find_by(id: params[:id])
        @topics = Topic.where(organization_id: [current_user.organization_id, nil]).includes(:conversations).load
    end

    def create
        @topic = Topic.new(topic_params)
        if @topic.save
            flash[:notice] = 'Topic added!'
            redirect_to root_path
        else
            flash.now[:error] = @topic.errors.map{|e,m|e.to_s.humanize.to_s + " " + m}
            respond_to do |format|
                format.js {render 'topics/create'}
            end
        end
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def update
        @topic = Topic.find(params[:id])

        if @topic.update_attributes(topic_params)
            redirect_to @topic
        else
            flash.now[:error] = @topic.errors.map{|e,m|e.to_s.humanize.to_s + " " + m}
            render 'edit'
        end
    end

    def destroy
        @topic = Topic.find(params[:id])
        @topic.conversations.destroy_all
        @topic.destroy
        flash[:notice] = "Topic deleted"
        redirect_to root_path
    end

    private

    def topic_params
        params.require(:topic).permit(:name, :organization_id)
    end
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/_form.html.erb
<div id='flash'></div>
<%= form_for @topic, html: {remote: true} do |f| %>
    <%= f.hidden_field :organization_id, :value => current_user.organization_id %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>

    <span><%= f.submit "Add!", class: 'btn btn-primary', remote: true %></span>
    <button type='button' class='btn' data-dismiss='modal' aria-hidden='true'>Cancel</button>
<% end %>

app/views/topics/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add topic</h4>
  <button type='button' class='close' data-dismiss='modal'>x</button>
</div>

<div class="modal-body">
    <%= render 'form' %>
</div>

app/views/topics/_topic.html.erb
<div class="topicname">
	<%= topic.name %>
	<%= link_to "X" , topic_path(topic), 'data-method' => :delete, :class => "delete", confirm:"Are you sure?" unless !current_user.is_admin? %>
</div>
<% topic.conversations.each do |conversation|%>
	<li>
		<%= link_to "#{conversation.title}", conversation_path(conversation) %>
	</li>
<% end %>

app/views/topics/create.js.erb
$("#AddTopicModal .modal-content").html('<%= j render partial: "topics/new" %>');
$('#flash').html(('<%= j render partial: "layouts/flash" %>'));
$("#AddTopicModal").modal();

app/views/topics/edit.html.erb
<div class="usermodal">
    <% if current_user && current_user.is_admin? %>
        <h1>Edit topic</h1>

        <%= render 'form' %>
    <% else %>
        <% controller.redirect_to root_path %>
    <% end %>
</div>

app/views/topics/new.js.erb
$("#AddTopicModal .modal-content").html('<%= j render partial: "topics/new"%>');
$("#AddTopicModal").modal();