config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "registrations"}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :dashboard
    resources :conversations
    resources :messages
    resources :topics
    resources :admin

    root 'conversations#index'

    get 'conversations_controller/index'
    get '/users', to: 'conversations#index'

    match 'users/:id' => 'users#edit', :via => :update, :as => :admin_update_user
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

    authenticate :user do
        mount ActionCable.server => '/cable'
    end
end

app/views/admin/index.html.erb
<div class="usermodal">
	<h1>User database</h1>
	<p>Manage your users here.</p>
	<div class="user-row">
		<div class="column top">Nickname</div>
		<div class="column top">First name</div>
		<div class="column top">Last name</div>
		<div class="column top">Admin?</div>
		<div class="column top">Email</div>
		<div class="column top">Actions</div>
	</div>
	<% @users.each do |user| %>
		<div class="user-row">
			<div class="column"><%= user.nickname %></div>
			<div class="column"><%= user.firstname %></div>
			<div class="column"><%= user.lastname %></div>
			<div class="column"><%= user.admin %></div>
			<div class="column"><%= user.email %></div>
			<div class="column">
				<%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %>
			</div>
		</div>
	<% end %>
</div>